language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: Test
      name: "Linting"
      script: "yarn lint"
    - script: yarn test:ci
      name: "Produce coverage"
    - stage: Build
      node_js: "10"
      name: "Webpack build"
      script: yarn build:ci
      before_deploy:
        # somehow this file get's some changes...
        - git checkout -- packages/webgis4u-cli/src/main.js
        - git config --global user.email eaa@github.com
        - git config --global user.name eaa-deploy-bot
        - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" > /dev/null 2>&1
        - git checkout master
        - echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: yarn deploy:ci
        skip_cleanup: true
        on:
          branch: master
    - stage: Docs
      name: "Generate docs"
      # Only generate docs for branch master
      if: branch = master
      script: yarn build:docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN_GHPAGES
        local-dir: packages/webgis4u/doc
        on:
          branch: master

